version: "3.9"
services:
  fairgame:
    image: fairgame:latest
    environment:
      SPRING_PROFILE: prod
      POSTGRES_URL: jdbc:postgresql://postgres:5432/FairGame
      POSTGRES_PASSWORD: postgres_secret
      MONGO_URL: mongodb://mongo:27017/FairGame
      REDIS_URL: redis://redis:6379
    ports:
      - "11235:11235"
    depends_on:
      - postgres
      - redis
      - mongo
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_secret
      POSTGRES_DB: FairGame
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db
      - mongo_config:/data/configdb
  redis:
    image: redis:latest
    ports:
      - "6666:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  mongo_data:
  mongo_config:
  redis_data: